services:
  backend:
    build:
      context: ./iphbackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./iphbackend/db:/usr/src/app/db

  frontend:
    build:
      context: ./itauproducthubfe
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend